### ISSUE TITLE
Can't find boost python library

### ISSUE THREAD

**Issue by jonassorgenfrei** [egor-tensin/build-boost#7]
Using this action to build python boost library i get the following error when running a cmake file with: 
```
# boost
set(Boost_NO_SYSTEM_PATHS true)
set (Boost_USE_STATIC_LIBS OFF CACHE BOOL "use static libraries from Boost")
set (Boost_USE_MULTITHREADED ON)
set (BUILD_SHARED_LIBS ON)
find_package(Boost REQUIRED COMPONENTS python REQUIRED)
```

Action Setup:
```
jobs:
  build:
    name: Build and Test
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ["3.9"]
        
    steps:
    - name: Checkout branch
      uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
          python-version: ${{ matrix.python-version }}
    - name: Get cmake
      uses: lukka/get-cmake@latest
    - name: Build Boost
      id: boost
      uses: egor-tensin/build-boost@v1
      with:
        version: 1.78.0
        libraries: headers system python
        platform: x64
        configuration: Release
        toolset: vs2022
    - name: Configure
      run: |
        mkdir build
        cd build
        cmake .. -D "BOOST_ROOT=${{ steps.boost.outputs.root }}" -D "BOOST_LIBRARYDIR=${{ steps.boost.outputs.librarydir }}" 
      env:
        BOOST_ROOT: ${{ steps.boost.outputs.root }}
```
`
CMake can't find libraries: 
   Could NOT find Boost (missing: python) (found version "1.78.0")
`

Is there anything i do wrong?
